services:
  localstack:
    image: localstack/localstack:latest
    container_name: project-tracker-localstack
    ports:
      - "4566:4566"  # LocalStack gateway
      - "4571:4571"  # LocalStack health endpoint
    environment:
      - SERVICES=s3,sqs,sns,lambda,dynamodb,secretsmanager,ses
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - project-tracker-network

networks:
  project-tracker-network:
    driver: bridge

