AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Email-based AI Project Tracking System

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  ProjectDomain:
    Type: String
    Description: Domain name for email receiving
  
  OpenAIKeySecretName:
    Type: String
    Default: openai-api-key
    Description: Name of the Secrets Manager secret containing OpenAI API key

Globals:
  Function:
    Runtime: python3.11
    Timeout: 300
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        AWS_REGION: !Ref AWS::Region
        PROJECT_DOMAIN: !Ref ProjectDomain
        OPENAI_API_KEY_SECRET: !Ref OpenAIKeySecretName
        EMAIL_BUCKET: !Ref EmailBucket
        PROJECTS_TABLE: !Ref ProjectsTable
        EVENTS_TABLE: !Ref EventsTable
        USERS_TABLE: !Ref UsersTable
        ORGANIZATIONS_TABLE: !Ref OrganizationsTable
        API_USAGE_TABLE: !Ref APIUsageTable

Resources:
  # S3 Bucket for Email Storage
  EmailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub project-emails-${AWS::AccountId}-${Environment}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldEmails
            Status: Enabled
            ExpirationInDays: 90

  # S3 Bucket Policy for SES
  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub ${EmailBucket.Arn}/*
            Condition:
              StringEquals:
                aws:Referer: !Ref AWS::AccountId

  # SNS Topic for Email Notifications
  EmailReceivedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub email-received-${Environment}
      DisplayName: Email Received Notifications
      KmsMasterKeyId: alias/aws/sns

  # SQS Queue for Email Processing
  EmailProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub email-processing-queue-${Environment}
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EmailProcessingDLQ.Arn
        maxReceiveCount: 3
      KmsMasterKeyId: alias/aws/sqs

  # Dead Letter Queue
  EmailProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub email-processing-dlq-${Environment}
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: alias/aws/sqs

  # Subscribe SQS to SNS
  EmailQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref EmailReceivedTopic
      Endpoint: !GetAtt EmailProcessingQueue.Arn

  # Allow SNS to send messages to SQS
  EmailQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EmailProcessingQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt EmailProcessingQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref EmailReceivedTopic

  # DynamoDB Tables
  
  # Organizations Table - Multi-tenant management
  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ProjectTracking-Organizations-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: organization_id
          AttributeType: S
        - AttributeName: email_address
          AttributeType: S
        - AttributeName: subdomain
          AttributeType: S
      KeySchema:
        - AttributeName: organization_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email_address-index
          KeySchema:
            - AttributeName: email_address
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: subdomain-index
          KeySchema:
            - AttributeName: subdomain
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false  # Enable in production

  # Projects Table - Updated for multi-tenancy
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ProjectTracking-Projects-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: organization_id
          AttributeType: S
        - AttributeName: project_id_created_at
          AttributeType: S
        - AttributeName: client_email
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: organization_id
          KeyType: HASH
        - AttributeName: project_id_created_at
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: client_email-index
          KeySchema:
            - AttributeName: client_email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: organization_id-status-index
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false  # Enable in production

  # Events Table - Updated for multi-tenancy
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ProjectTracking-Events-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: organization_id_project_id
          AttributeType: S
        - AttributeName: event_timestamp
          AttributeType: N
        - AttributeName: organization_id
          AttributeType: S
      KeySchema:
        - AttributeName: organization_id_project_id
          KeyType: HASH
        - AttributeName: event_timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: organization_id-index
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
            - AttributeName: event_timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false  # Enable in production

  # Users Table - Updated for multi-tenancy
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ProjectTracking-Users-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_email
          AttributeType: S
        - AttributeName: organization_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: organization_id-index
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

  # API Usage Tracking Table - Real-time cost monitoring
  APIUsageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ProjectTracking-APIUsage-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: organization_id_date
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: organization_id
          AttributeType: S
      KeySchema:
        - AttributeName: organization_id_date
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: organization_id-index
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true  # Auto-delete old usage data after 90 days

  # Lambda Functions
  EmailProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub email-processor-${Environment}
      CodeUri: ../src/lambdas/email_processor/
      Handler: handler.lambda_handler
      Description: Process incoming emails from SES
      Environment:
        Variables:
          EMAIL_QUEUE_URL: !Ref EmailProcessingQueue
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref EmailBucket
        - S3WritePolicy:
            BucketName: !Ref EmailBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrganizationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref APIUsageTable
        - SQSPollerPolicy:
            QueueName: !GetAtt EmailProcessingQueue.QueueName
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${OpenAIKeySecretName}-*
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EmailProcessingQueue.Arn
            BatchSize: 1

  AIOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ai-orchestrator-${Environment}
      CodeUri: ../src/lambdas/ai_orchestrator/
      Handler: handler.lambda_handler
      Description: AI orchestration for estimates and analysis
      Timeout: 600  # 10 minutes for estimate generation
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref EmailBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrganizationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref APIUsageTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${OpenAIKeySecretName}-*

  ReplySenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub reply-sender-${Environment}
      CodeUri: ../src/lambdas/reply_sender/
      Handler: handler.lambda_handler
      Description: Send email replies via SES
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref EmailBucket
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
                - ses:SendEmail
              Resource: '*'

  # CloudWatch Log Groups
  EmailProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/email-processor-${Environment}
      RetentionInDays: 30

  AIOrchestratorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/ai-orchestrator-${Environment}
      RetentionInDays: 30

  ReplySenderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/reply-sender-${Environment}
      RetentionInDays: 30

  # CloudWatch Alarms
  EmailProcessorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub email-processor-errors-${Environment}
      AlarmDescription: Alert when email processor has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref EmailProcessorFunction

  DLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub email-dlq-messages-${Environment}
      AlarmDescription: Alert when messages end up in DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt EmailProcessingDLQ.QueueName

  # Cognito User Pool for Authentication
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub project-tracker-users-${Environment}
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: organization_id
          AttributeDataType: String
          Mutable: false
        - Name: role
          AttributeDataType: String
          Mutable: true
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserPoolTags:
        Environment: !Ref Environment
        Application: project-tracker

  # Cognito User Pool Client for Web App
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub project-tracker-web-${Environment}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1  # 1 hour
      IdTokenValidity: 1  # 1 hour
      RefreshTokenValidity: 30  # 30 days
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      ReadAttributes:
        - email
        - custom:organization_id
        - custom:role
      WriteAttributes:
        - email

  # Cognito User Pool Domain
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub project-tracker-${AWS::AccountId}-${Environment}
      UserPoolId: !Ref UserPool

Outputs:
  EmailBucket:
    Description: S3 bucket for email storage
    Value: !Ref EmailBucket
    Export:
      Name: !Sub ${AWS::StackName}-EmailBucket

  EmailReceivedTopicArn:
    Description: SNS topic ARN for email notifications
    Value: !Ref EmailReceivedTopic
    Export:
      Name: !Sub ${AWS::StackName}-EmailReceivedTopicArn

  EmailQueueUrl:
    Description: SQS queue URL for email processing
    Value: !Ref EmailProcessingQueue
    Export:
      Name: !Sub ${AWS::StackName}-EmailQueueUrl

  ProjectsTableName:
    Description: DynamoDB Projects table name
    Value: !Ref ProjectsTable
    Export:
      Name: !Sub ${AWS::StackName}-ProjectsTable

  EventsTableName:
    Description: DynamoDB Events table name
    Value: !Ref EventsTable
    Export:
      Name: !Sub ${AWS::StackName}-EventsTable

  UsersTableName:
    Description: DynamoDB Users table name
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${AWS::StackName}-UsersTable

  OrganizationsTableName:
    Description: DynamoDB Organizations table name
    Value: !Ref OrganizationsTable
    Export:
      Name: !Sub ${AWS::StackName}-OrganizationsTable

  APIUsageTableName:
    Description: DynamoDB API Usage table name
    Value: !Ref APIUsageTable
    Export:
      Name: !Sub ${AWS::StackName}-APIUsageTable

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  UserPoolDomain:
    Description: Cognito User Pool Domain
    Value: !Ref UserPoolDomain
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolDomain

